In [6]:
#Biplab Shah/2332921
#A matrix A's determinant, inverse, and multiplication can be calculated using a Python program.
import numpy as np

# asking the user for their input on the matrix values
def get_user_matrix():
    while True:
        try:
            values = []
            for i in range(3):
                row = []
                for j in range(3):
                    value = int(input(f"Enter value ({i+1}, {j+1}): "))
                    row.append(value)
                values.append(row)
            A = np.array(values) # create a multidimensional array formatted into 3x3 matrix
            break
        except ValueError:
            print("Error: enter integers only")
    return A

# the matrix values printed
def print_matrix_values(A):
    print("A =\n", A)
    print("Values in A are: ", A.flatten())

# Determine the matrix's determinant.
def find_determinant(A):
    detA = np.linalg.det(A)
    np.set_printoptions(precision=2, suppress=True)
    print("The determinant of A is: ", detA)

# function to determine the matrix's inverse
def find_inverse(A):
    try:
        invA = np.linalg.inv(A)
        np.set_printoptions(precision=2, suppress=True)
        print("The inverse of A is: \n", invA)
    except np.linalg.LinAlgError:
        print("The matrix A is singular.")

# Count the number of values in the matrix that are more than or equal to 10 with this function
def count_large_values(A, threshold):
    count = np.count_nonzero(A >= threshold)
    print("Number of values which are >= ", threshold, " is: ", count)

# according to question 1, functions to carry out the matrix operations A*A and A*A*A 
def matrix_operations(A):
    A2 = np.dot(A, A)
    A3 = np.dot(A2, A)
    print("A*A =\n", A2)
    print("A*A*A =\n", A3)

def main():
    A = get_user_matrix()
    print_matrix_values(A)
    find_determinant(A)
    find_inverse(A)
    count_large_values(A, 10)
    matrix_operations(A)

def run_program():
    while True:
        main()
        rerun = input("Do you want to use the program again? (Y/N) ").upper()
        if rerun == "N":
            break
    exit_program()

def exit_program():
    print("Program has concluded. Thank you for using it.")

run_program()


Enter value (1, 1): 2
Enter value (1, 2): \
Error: enter integers only
Enter value (1, 1): a
Error: enter integers only
Enter value (1, 1): 23
Enter value (1, 2): 67
Enter value (1, 3): 8
Enter value (2, 1): 9
Enter value (2, 2): 0
Enter value (2, 3): 5
Enter value (3, 1): 78
Enter value (3, 2): 9
Enter value (3, 3): 8
A =
 [[23 67  8]
 [ 9  0  5]
 [78  9  8]]
Values in A are:  [23 67  8  9  0  5 78  9  8]
The determinant of A is:  20919.00000000001
The inverse of A is: 
 [[-0.   -0.02  0.02]
 [ 0.02 -0.02 -0.  ]
 [ 0.    0.24 -0.03]]
Number of values which are >=  10  is:  3
A*A =
 [[1756 1613  583]
 [ 597  648  112]
 [2499 5298  733]]
A*A*A =
 [[100379 122899  26777]
 [ 28299  41007   8912]
 [162333 174030  52346]]
Do you want to use the program again? (Y/N) n
Program has concluded. Thank you for using it.


In [13]:
#Biplab Shah/2332921
# A python program to find traces of matrices of any size and demonstrate traces of the matrices given in the question
import numpy as np

# Define a function to calculate the trace of a matrix
def matrixtrace(matrix):
    # Calculate the sum of the diagonal elements of the matrix
    return np.trace(matrix)

# Define a function to calculate the sum of the diagonal elements of a matrix
def diagonalsum(matrix):
    # Calculate the sum of the diagonal elements of the matrix
    return np.trace(matrix)

# Define the matrices that need to be evaluated
matrix_1 = [[3, 2], [3, 6]]
matrix_2 = [[2, 1, 7], [5, 8, 1], [5, 2, 1]]
matrix_3 = np.random.randint(10, size=(4, 4))
matrix_4 = np.random.randint(10, size=(5, 5))
matrix_5 = np.random.randint(10, size=(6, 6))
matrix_6 = np.random.randint(10, size=(7, 7))

# Evaluate the trace of each matrix and print the result
print("The trace of matrix_1 is:", matrixtrace(np.array(matrix_1)))# trace of matrix of values define by the user
print("The trace of matrix_2 is:", matrixtrace(np.array(matrix_2)))# trace of matrix of values define by the user
print("The trace of 4x4 matrix is:", matrixtrace(matrix_3))# trace of 4x4 matrix with each cell of the matrix containing a number between 0-9
print("The trace of 5x5 matrix is:", matrixtrace(matrix_4))# trace of 5x5 matrix with each cell of the matrix containing a number between 0-9
print("The trace of 6x6 matrix is:", matrixtrace(matrix_5))# trace of 6x6 matrix with each cell of the matrix containing a number between 0-9
print("The trace of 7x7 matrix is:", matrixtrace(matrix_6))# trace of 7x7 matrix with each cell of the matrix containing a number between 0-9

# Evaluate the sum of the diagonal elements of each matrix and print the result
matrix_7 = [[2, 1, 4], [9, 8, 7], [3, 1, 8]]
matrix_8 = np.random.randint(10, size=(4, 4))
matrix_9 = np.random.randint(10, size=(6, 6))

print("The sum of diagonal elements in matrix_7 is:", diagonalsum(np.array(matrix_7)))
print("The sum of diagonal elements in matrix_8 is:", diagonalsum(matrix_8))
print("The sum of diagonal elements in matrix_9 is:", diagonalsum(matrix_9))


The trace of matrix_1 is: 9
The trace of matrix_2 is: 11
The trace of 4x4 matrix is: 22
The trace of 5x5 matrix is: 25
The trace of 6x6 matrix is: 25
The trace of 7x7 matrix is: 33
The sum of diagonal elements in matrix_7 is: 18
The sum of diagonal elements in matrix_8 is: 20
The sum of diagonal elements in matrix_9 is: 26


In [5]:
#Biplab Shah/2332921
# A Python program that calculates the required recursive calls and value of A(2.3) using Ackermann's function as given in the question
# Defining the Ackermann function(A) which takes two arguments m and n and passes in the later stages of the program
count=0;#pertaining count as default to 0 at a starting position
def A(m, n):
    global count
    count += 1 s#counts recursive cells
    if m == 0:
        return n + 1  
    elif m > 0 and n == 0:
        return A(m - 1, 1)
    elif m > 0 and n > 0:
        return A(m - 1, A(m, n - 1))
# Pass 2 and 3 as arguments to the m and n parameters of the A function and store the result in a variable named result
result = A(2, 3)
# Print the number of recursive calls required to evaluate A(2, 3)
print(f"value of A(2, 3) is {result}");#f for formatted printing
print(f"recursive calls = {count} .")


value of A(2, 3) is 9
recursive calls = 44 .
